require:
  - rubocop-performance
  - rubocop-rspec

inherit_from:
  - .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Lint/EmptyBlock:
  Exclude:
    - 'spec/onlyoffice_rspec_parser/spec_examples/duplicates/no_dublicates_spec.rb'
    - 'spec/onlyoffice_rspec_parser/spec_examples/duplicates/one_dublicates_spec.rb'
    - 'spec/onlyoffice_rspec_parser/spec_examples/rspec_parsed/single_it_spec.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/onlyoffice_rspec_parser/spec_examples/**/*'

RSpec/ExpectInHook:
  Exclude:
    - 'spec/onlyoffice_rspec_parser/spec_examples/rspec_parsed/expect_after_it_spec.rb'

RSpec/HooksBeforeExamples:
  Exclude:
    - 'spec/onlyoffice_rspec_parser/spec_examples/rspec_parsed/expect_after_it_spec.rb'

RSpec/NoExpectationExample:
  Exclude:
    - 'spec/onlyoffice_rspec_parser/spec_examples/**/*'

RSpec/RepeatedDescription:
  Exclude:
    - 'spec/onlyoffice_rspec_parser/spec_examples/duplicates/one_dublicates_spec.rb'

RSpec/RepeatedExample:
  Exclude:
    - 'spec/onlyoffice_rspec_parser/spec_examples/duplicates/*'

RSpec/IdenticalEqualityAssertion:
  Exclude:
    - 'spec/onlyoffice_rspec_parser/spec_examples/rspec_parsed/expect_after_it_spec.rb'
