require:
  - rubocop-performance
  - rubocop-rspec

inherit_from:
  - .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5

RSpec/DescribeClass:
  Exclude:
    - 'spec/onlyoffice_rspec_parser/spec_examples/**/*'

RSpec/ExpectInHook:
  Exclude:
    - 'spec/onlyoffice_rspec_parser/spec_examples/rspec_parsed/expect_after_it_spec.rb'

RSpec/HooksBeforeExamples:
  Exclude:
    - 'spec/onlyoffice_rspec_parser/spec_examples/rspec_parsed/expect_after_it_spec.rb'

RSpec/RepeatedDescription:
  Exclude:
    - 'spec/onlyoffice_rspec_parser/spec_examples/duplicates/one_dublicates_spec.rb'

RSpec/RepeatedExample:
  Exclude:
    - 'spec/onlyoffice_rspec_parser/spec_examples/duplicates/*'
